server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: /home/tg/Git/pacoca-config
          default-label: master
          clone-on-start: true
          search-paths:
            - '{application}'
            - toggles